// This file is auto-generated by @hey-api/openapi-ts

export const ArtifactOutSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        capture_id: {
            type: 'string',
            title: 'Capture Id'
        },
        artifact_type: {
            type: 'string',
            title: 'Artifact Type'
        },
        content: {
            additionalProperties: true,
            type: 'object',
            title: 'Content'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        source_text: {
            type: 'string',
            title: 'Source Text'
        }
    },
    type: 'object',
    required: ['id', 'capture_id', 'artifact_type', 'content', 'created_at', 'source_text'],
    title: 'ArtifactOut'
} as const;

export const CaptureCreateSchema = {
    properties: {
        mode: {
            type: 'string',
            title: 'Mode'
        },
        raw_content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Content'
        },
        media_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Key'
        }
    },
    type: 'object',
    required: ['mode'],
    title: 'CaptureCreate'
} as const;

export const CaptureOutSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        mode: {
            type: 'string',
            title: 'Mode'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'mode', 'status', 'created_at'],
    title: 'CaptureOut'
} as const;

export const FlashcardPairSchema = {
    properties: {
        front: {
            type: 'string',
            title: 'Front'
        },
        back: {
            type: 'string',
            title: 'Back'
        }
    },
    type: 'object',
    required: ['front', 'back'],
    title: 'FlashcardPair'
} as const;

export const FlashcardTransformResponseSchema = {
    properties: {
        skill_name: {
            type: 'string',
            const: 'generate_flashcard',
            title: 'Skill Name'
        },
        cards: {
            items: {
                '$ref': '#/components/schemas/FlashcardPair'
            },
            type: 'array',
            title: 'Cards'
        },
        source_summary: {
            type: 'string',
            title: 'Source Summary'
        }
    },
    type: 'object',
    required: ['skill_name', 'cards', 'source_summary'],
    title: 'FlashcardTransformResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const NoteTransformResponseSchema = {
    properties: {
        skill_name: {
            type: 'string',
            const: 'generate_note',
            title: 'Skill Name'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        body_markdown: {
            type: 'string',
            title: 'Body Markdown'
        },
        key_points: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Key Points'
        }
    },
    type: 'object',
    required: ['skill_name', 'title', 'body_markdown', 'key_points'],
    title: 'NoteTransformResponse'
} as const;

export const QuizQuestionSchema = {
    properties: {
        stem: {
            type: 'string',
            title: 'Stem'
        },
        options: {
            items: {
                type: 'string'
            },
            type: 'array',
            minItems: 2,
            title: 'Options'
        },
        correct_index: {
            type: 'integer',
            title: 'Correct Index'
        },
        explanation: {
            type: 'string',
            title: 'Explanation'
        }
    },
    type: 'object',
    required: ['stem', 'options', 'correct_index', 'explanation'],
    title: 'QuizQuestion'
} as const;

export const QuizTransformResponseSchema = {
    properties: {
        skill_name: {
            type: 'string',
            const: 'generate_quiz',
            title: 'Skill Name'
        },
        questions: {
            items: {
                '$ref': '#/components/schemas/QuizQuestion'
            },
            type: 'array',
            title: 'Questions'
        }
    },
    type: 'object',
    required: ['skill_name', 'questions'],
    title: 'QuizTransformResponse'
} as const;

export const SuggestTagsRequestSchema = {
    properties: {
        text: {
            type: 'string',
            minLength: 1,
            title: 'Text'
        },
        existing_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Existing Tags'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'SuggestTagsRequest'
} as const;

export const SuggestTagsResponseSchema = {
    properties: {
        suggestions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Suggestions'
        }
    },
    type: 'object',
    required: ['suggestions'],
    title: 'SuggestTagsResponse'
} as const;

export const TagOutSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        mastery_score: {
            type: 'number',
            title: 'Mastery Score'
        }
    },
    type: 'object',
    required: ['id', 'name', 'color', 'mastery_score'],
    title: 'TagOut'
} as const;

export const TransformRequestSchema = {
    properties: {
        text: {
            type: 'string',
            minLength: 1,
            title: 'Text'
        },
        tier: {
            type: 'string',
            enum: ['free', 'paid'],
            title: 'Tier',
            default: 'free'
        },
        skill_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Skill Name'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'TransformRequest'
} as const;

export const UserClaimsSchema = {
    properties: {
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        tier: {
            type: 'string',
            title: 'Tier',
            default: 'free'
        }
    },
    type: 'object',
    required: ['user_id'],
    title: 'UserClaims'
} as const;

export const UserProfileInSchema = {
    properties: {
        learning_type: {
            type: 'string',
            enum: ['language_learner', 'professional', 'student', 'generic'],
            title: 'Learning Type'
        }
    },
    type: 'object',
    required: ['learning_type'],
    title: 'UserProfileIn'
} as const;

export const UserProfileOutSchema = {
    properties: {
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        learning_type: {
            type: 'string',
            enum: ['language_learner', 'professional', 'student', 'generic'],
            title: 'Learning Type'
        }
    },
    type: 'object',
    required: ['user_id', 'learning_type'],
    title: 'UserProfileOut'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;