// This file is auto-generated by @hey-api/openapi-ts

export const ActivitySummarySchema = {
    properties: {
        mistakes_resolved_this_week: {
            type: 'integer',
            title: 'Mistakes Resolved This Week'
        },
        tags_improved_this_week: {
            type: 'integer',
            title: 'Tags Improved This Week'
        }
    },
    type: 'object',
    required: ['mistakes_resolved_this_week', 'tags_improved_this_week'],
    title: 'ActivitySummary'
} as const;

export const ArtifactOutSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        capture_id: {
            type: 'string',
            title: 'Capture Id'
        },
        artifact_type: {
            type: 'string',
            title: 'Artifact Type'
        },
        content: {
            additionalProperties: true,
            type: 'object',
            title: 'Content'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        source_text: {
            type: 'string',
            title: 'Source Text'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'draft'
        }
    },
    type: 'object',
    required: ['id', 'capture_id', 'artifact_type', 'content', 'created_at', 'source_text'],
    title: 'ArtifactOut'
} as const;

export const CaptureCreateSchema = {
    properties: {
        mode: {
            type: 'string',
            title: 'Mode'
        },
        raw_content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Content'
        },
        media_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Key'
        }
    },
    type: 'object',
    required: ['mode'],
    title: 'CaptureCreate'
} as const;

export const CaptureOutSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        mode: {
            type: 'string',
            title: 'Mode'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'mode', 'status', 'created_at'],
    title: 'CaptureOut'
} as const;

export const DrillItemOutSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        artifact_id: {
            type: 'string',
            title: 'Artifact Id'
        },
        item_type: {
            type: 'string',
            title: 'Item Type'
        },
        content: {
            additionalProperties: true,
            type: 'object',
            title: 'Content'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        source_text: {
            type: 'string',
            title: 'Source Text'
        }
    },
    type: 'object',
    required: ['id', 'artifact_id', 'item_type', 'content', 'tags', 'source_text'],
    title: 'DrillItemOut'
} as const;

export const FlashcardPairSchema = {
    properties: {
        front: {
            type: 'string',
            title: 'Front'
        },
        back: {
            type: 'string',
            title: 'Back'
        }
    },
    type: 'object',
    required: ['front', 'back'],
    title: 'FlashcardPair'
} as const;

export const FlashcardTransformResponseSchema = {
    properties: {
        skill_name: {
            type: 'string',
            const: 'generate_flashcard',
            title: 'Skill Name'
        },
        cards: {
            items: {
                '$ref': '#/components/schemas/FlashcardPair'
            },
            type: 'array',
            title: 'Cards'
        },
        source_summary: {
            type: 'string',
            title: 'Source Summary'
        },
        suggested_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Suggested Tags',
            default: []
        },
        artifact_id: {
            type: 'string',
            title: 'Artifact Id',
            default: ''
        }
    },
    type: 'object',
    required: ['skill_name', 'cards', 'source_summary'],
    title: 'FlashcardTransformResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MasteryResponseSchema = {
    properties: {
        tags: {
            items: {
                '$ref': '#/components/schemas/TagMastery'
            },
            type: 'array',
            title: 'Tags'
        },
        activity: {
            '$ref': '#/components/schemas/ActivitySummary'
        },
        streak_days: {
            type: 'integer',
            title: 'Streak Days'
        },
        xp: {
            type: 'integer',
            title: 'Xp'
        }
    },
    type: 'object',
    required: ['tags', 'activity', 'streak_days', 'xp'],
    title: 'MasteryResponse'
} as const;

export const NoteTransformResponseSchema = {
    properties: {
        skill_name: {
            type: 'string',
            const: 'generate_note',
            title: 'Skill Name'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        body_markdown: {
            type: 'string',
            title: 'Body Markdown'
        },
        key_points: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Key Points'
        },
        suggested_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Suggested Tags',
            default: []
        },
        artifact_id: {
            type: 'string',
            title: 'Artifact Id',
            default: ''
        }
    },
    type: 'object',
    required: ['skill_name', 'title', 'body_markdown', 'key_points'],
    title: 'NoteTransformResponse'
} as const;

export const QueueResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/DrillItemOut'
            },
            type: 'array',
            title: 'Items'
        },
        new_count: {
            type: 'integer',
            title: 'New Count'
        },
        reviewed_count: {
            type: 'integer',
            title: 'Reviewed Count'
        }
    },
    type: 'object',
    required: ['items', 'new_count', 'reviewed_count'],
    title: 'QueueResponse'
} as const;

export const QuizQuestionSchema = {
    properties: {
        stem: {
            type: 'string',
            title: 'Stem'
        },
        options: {
            items: {
                type: 'string'
            },
            type: 'array',
            minItems: 2,
            title: 'Options'
        },
        correct_index: {
            type: 'integer',
            title: 'Correct Index'
        },
        explanation: {
            type: 'string',
            title: 'Explanation'
        }
    },
    type: 'object',
    required: ['stem', 'options', 'correct_index', 'explanation'],
    title: 'QuizQuestion'
} as const;

export const QuizTransformResponseSchema = {
    properties: {
        skill_name: {
            type: 'string',
            const: 'generate_quiz',
            title: 'Skill Name'
        },
        questions: {
            items: {
                '$ref': '#/components/schemas/QuizQuestion'
            },
            type: 'array',
            title: 'Questions'
        },
        suggested_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Suggested Tags',
            default: []
        },
        artifact_id: {
            type: 'string',
            title: 'Artifact Id',
            default: ''
        }
    },
    type: 'object',
    required: ['skill_name', 'questions'],
    title: 'QuizTransformResponse'
} as const;

export const RecordEventRequestSchema = {
    properties: {
        item_id: {
            type: 'string',
            title: 'Item Id'
        },
        outcome: {
            type: 'string',
            enum: ['passed', 'failed'],
            title: 'Outcome'
        }
    },
    type: 'object',
    required: ['item_id', 'outcome'],
    title: 'RecordEventRequest'
} as const;

export const RecordEventResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        xp_gained: {
            type: 'integer',
            title: 'Xp Gained'
        }
    },
    type: 'object',
    required: ['id', 'xp_gained'],
    title: 'RecordEventResponse'
} as const;

export const SuggestTagsRequestSchema = {
    properties: {
        text: {
            type: 'string',
            minLength: 1,
            title: 'Text'
        },
        existing_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Existing Tags'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'SuggestTagsRequest'
} as const;

export const SuggestTagsResponseSchema = {
    properties: {
        suggestions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Suggestions'
        }
    },
    type: 'object',
    required: ['suggestions'],
    title: 'SuggestTagsResponse'
} as const;

export const TagMasterySchema = {
    properties: {
        tag: {
            type: 'string',
            title: 'Tag'
        },
        item_count: {
            type: 'integer',
            title: 'Item Count'
        },
        passed_count: {
            type: 'integer',
            title: 'Passed Count'
        },
        mastery_pct: {
            type: 'number',
            title: 'Mastery Pct'
        },
        above_threshold: {
            type: 'boolean',
            title: 'Above Threshold'
        }
    },
    type: 'object',
    required: ['tag', 'item_count', 'passed_count', 'mastery_pct', 'above_threshold'],
    title: 'TagMastery'
} as const;

export const TagOutSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        bg: {
            type: 'string',
            title: 'Bg'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['name', 'bg', 'text'],
    title: 'TagOut'
} as const;

export const TransformRequestSchema = {
    properties: {
        text: {
            type: 'string',
            minLength: 1,
            title: 'Text'
        },
        tier: {
            type: 'string',
            enum: ['free', 'paid'],
            title: 'Tier',
            default: 'free'
        },
        skill_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Skill Name'
        },
        source_artifact_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Artifact Id'
        },
        confirmed_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Confirmed Tags'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'TransformRequest'
} as const;

export const UserClaimsSchema = {
    properties: {
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        tier: {
            type: 'string',
            title: 'Tier',
            default: 'free'
        }
    },
    type: 'object',
    required: ['user_id'],
    title: 'UserClaims'
} as const;

export const UserProfileInSchema = {
    properties: {
        learning_type: {
            type: 'string',
            enum: ['language_learner', 'professional', 'student', 'generic'],
            title: 'Learning Type'
        }
    },
    type: 'object',
    required: ['learning_type'],
    title: 'UserProfileIn'
} as const;

export const UserProfileOutSchema = {
    properties: {
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        learning_type: {
            type: 'string',
            enum: ['language_learner', 'professional', 'student', 'generic'],
            title: 'Learning Type'
        }
    },
    type: 'object',
    required: ['user_id', 'learning_type'],
    title: 'UserProfileOut'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;