// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { TransformCaptureApiV1CapturesTransformPostData, TransformCaptureApiV1CapturesTransformPostResponse, ListCapturesApiV1CapturesGetResponse, CreateCaptureApiV1CapturesPostData, CreateCaptureApiV1CapturesPostResponse, GetCaptureApiV1CapturesCaptureIdGetData, GetCaptureApiV1CapturesCaptureIdGetResponse, GetArtifactApiV1ArtifactsArtifactIdGetData, GetArtifactApiV1ArtifactsArtifactIdGetResponse, ListArtifactsApiV1ArtifactsGetResponse, ListTagsApiV1TagsGetResponse, GetTagApiV1TagsTagIdGetData, GetTagApiV1TagsTagIdGetResponse, GetMeApiV1UsersMeGetResponse, GetProfileApiV1UsersProfileGetResponse, CreateProfileApiV1UsersProfilePostData, CreateProfileApiV1UsersProfilePostResponse, HealthHealthGetResponse } from './types.gen';

/**
 * Transform Capture
 * @param data The data for the request.
 * @param data.requestBody
 * @returns TransformResponse Successful Response
 * @throws ApiError
 */
export const transformCaptureApiV1CapturesTransformPost = (data: TransformCaptureApiV1CapturesTransformPostData): CancelablePromise<TransformCaptureApiV1CapturesTransformPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/captures/transform',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * List Captures
 * @returns CaptureOut Successful Response
 * @throws ApiError
 */
export const listCapturesApiV1CapturesGet = (): CancelablePromise<ListCapturesApiV1CapturesGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/captures/'
    });
};

/**
 * Create Capture
 * @param data The data for the request.
 * @param data.requestBody
 * @returns CaptureOut Successful Response
 * @throws ApiError
 */
export const createCaptureApiV1CapturesPost = (data: CreateCaptureApiV1CapturesPostData): CancelablePromise<CreateCaptureApiV1CapturesPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/captures/',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Get Capture
 * @param data The data for the request.
 * @param data.captureId
 * @returns CaptureOut Successful Response
 * @throws ApiError
 */
export const getCaptureApiV1CapturesCaptureIdGet = (data: GetCaptureApiV1CapturesCaptureIdGetData): CancelablePromise<GetCaptureApiV1CapturesCaptureIdGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/captures/{capture_id}',
        path: {
            capture_id: data.captureId
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Get Artifact
 * @param data The data for the request.
 * @param data.artifactId
 * @returns ArtifactOut Successful Response
 * @throws ApiError
 */
export const getArtifactApiV1ArtifactsArtifactIdGet = (data: GetArtifactApiV1ArtifactsArtifactIdGetData): CancelablePromise<GetArtifactApiV1ArtifactsArtifactIdGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/artifacts/{artifact_id}',
        path: {
            artifact_id: data.artifactId
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * List Artifacts
 * @returns ArtifactOut Successful Response
 * @throws ApiError
 */
export const listArtifactsApiV1ArtifactsGet = (): CancelablePromise<ListArtifactsApiV1ArtifactsGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/artifacts/'
    });
};

/**
 * List Tags
 * @returns TagOut Successful Response
 * @throws ApiError
 */
export const listTagsApiV1TagsGet = (): CancelablePromise<ListTagsApiV1TagsGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/tags/'
    });
};

/**
 * Get Tag
 * @param data The data for the request.
 * @param data.tagId
 * @returns TagOut Successful Response
 * @throws ApiError
 */
export const getTagApiV1TagsTagIdGet = (data: GetTagApiV1TagsTagIdGetData): CancelablePromise<GetTagApiV1TagsTagIdGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/tags/{tag_id}',
        path: {
            tag_id: data.tagId
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Get Me
 * @returns UserClaims Successful Response
 * @throws ApiError
 */
export const getMeApiV1UsersMeGet = (): CancelablePromise<GetMeApiV1UsersMeGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/users/me'
    });
};

/**
 * Get Profile
 * @returns UserProfileOut Successful Response
 * @throws ApiError
 */
export const getProfileApiV1UsersProfileGet = (): CancelablePromise<GetProfileApiV1UsersProfileGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/users/profile'
    });
};

/**
 * Create Profile
 * @param data The data for the request.
 * @param data.requestBody
 * @returns UserProfileOut Successful Response
 * @throws ApiError
 */
export const createProfileApiV1UsersProfilePost = (data: CreateProfileApiV1UsersProfilePostData): CancelablePromise<CreateProfileApiV1UsersProfilePostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/users/profile',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Health
 * @returns string Successful Response
 * @throws ApiError
 */
export const healthHealthGet = (): CancelablePromise<HealthHealthGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/health'
    });
};