// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUploadUrlApiV1CapturesUploadUrlPostData, GetUploadUrlApiV1CapturesUploadUrlPostResponse, OcrCaptureApiV1CapturesOcrPostData, OcrCaptureApiV1CapturesOcrPostResponse, SuggestTagsApiV1CapturesSuggestTagsPostData, SuggestTagsApiV1CapturesSuggestTagsPostResponse, TransformCaptureApiV1CapturesTransformPostData, TransformCaptureApiV1CapturesTransformPostResponse, ListCapturesApiV1CapturesGetResponse, CreateCaptureApiV1CapturesPostData, CreateCaptureApiV1CapturesPostResponse, GetCaptureApiV1CapturesCaptureIdGetData, GetCaptureApiV1CapturesCaptureIdGetResponse, ListArtifactsApiV1ArtifactsGetResponse, GetArtifactApiV1ArtifactsArtifactIdGetData, GetArtifactApiV1ArtifactsArtifactIdGetResponse, SetArtifactTagsApiV1ArtifactsArtifactIdTagsPutData, SetArtifactTagsApiV1ArtifactsArtifactIdTagsPutResponse, ListTagsApiV1TagsGetResponse, GetMeApiV1UsersMeGetResponse, GetProfileApiV1UsersProfileGetResponse, CreateProfileApiV1UsersProfilePostData, CreateProfileApiV1UsersProfilePostResponse, GetQueueApiV1ReviewQueueGetData, GetQueueApiV1ReviewQueueGetResponse, RecordEventApiV1ReviewEventsPostData, RecordEventApiV1ReviewEventsPostResponse, GetMasteryApiV1ProfileMasteryGetResponse, HealthHealthGetResponse } from './types.gen';

/**
 * Get Upload Url
 * @param data The data for the request.
 * @param data.requestBody
 * @returns UploadUrlResponse Successful Response
 * @throws ApiError
 */
export const getUploadUrlApiV1CapturesUploadUrlPost = (data: GetUploadUrlApiV1CapturesUploadUrlPostData): CancelablePromise<GetUploadUrlApiV1CapturesUploadUrlPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/captures/upload-url',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Ocr Capture
 * @param data The data for the request.
 * @param data.requestBody
 * @returns OcrResponse Successful Response
 * @throws ApiError
 */
export const ocrCaptureApiV1CapturesOcrPost = (data: OcrCaptureApiV1CapturesOcrPostData): CancelablePromise<OcrCaptureApiV1CapturesOcrPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/captures/ocr',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Suggest Tags
 * @param data The data for the request.
 * @param data.requestBody
 * @returns SuggestTagsResponse Successful Response
 * @throws ApiError
 */
export const suggestTagsApiV1CapturesSuggestTagsPost = (data: SuggestTagsApiV1CapturesSuggestTagsPostData): CancelablePromise<SuggestTagsApiV1CapturesSuggestTagsPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/captures/suggest-tags',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Transform Capture
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const transformCaptureApiV1CapturesTransformPost = (data: TransformCaptureApiV1CapturesTransformPostData): CancelablePromise<TransformCaptureApiV1CapturesTransformPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/captures/transform',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * List Captures
 * @returns CaptureOut Successful Response
 * @throws ApiError
 */
export const listCapturesApiV1CapturesGet = (): CancelablePromise<ListCapturesApiV1CapturesGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/captures/'
    });
};

/**
 * Create Capture
 * @param data The data for the request.
 * @param data.requestBody
 * @returns CaptureOut Successful Response
 * @throws ApiError
 */
export const createCaptureApiV1CapturesPost = (data: CreateCaptureApiV1CapturesPostData): CancelablePromise<CreateCaptureApiV1CapturesPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/captures/',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Get Capture
 * @param data The data for the request.
 * @param data.captureId
 * @returns CaptureOut Successful Response
 * @throws ApiError
 */
export const getCaptureApiV1CapturesCaptureIdGet = (data: GetCaptureApiV1CapturesCaptureIdGetData): CancelablePromise<GetCaptureApiV1CapturesCaptureIdGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/captures/{capture_id}',
        path: {
            capture_id: data.captureId
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * List Artifacts
 * @returns ArtifactOut Successful Response
 * @throws ApiError
 */
export const listArtifactsApiV1ArtifactsGet = (): CancelablePromise<ListArtifactsApiV1ArtifactsGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/artifacts'
    });
};

/**
 * Get Artifact
 * @param data The data for the request.
 * @param data.artifactId
 * @returns ArtifactOut Successful Response
 * @throws ApiError
 */
export const getArtifactApiV1ArtifactsArtifactIdGet = (data: GetArtifactApiV1ArtifactsArtifactIdGetData): CancelablePromise<GetArtifactApiV1ArtifactsArtifactIdGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/artifacts/{artifact_id}',
        path: {
            artifact_id: data.artifactId
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Set Artifact Tags
 * @param data The data for the request.
 * @param data.artifactId
 * @param data.requestBody
 * @returns ArtifactOut Successful Response
 * @throws ApiError
 */
export const setArtifactTagsApiV1ArtifactsArtifactIdTagsPut = (data: SetArtifactTagsApiV1ArtifactsArtifactIdTagsPutData): CancelablePromise<SetArtifactTagsApiV1ArtifactsArtifactIdTagsPutResponse> => {
    return __request(OpenAPI, {
        method: 'PUT',
        url: '/api/v1/artifacts/{artifact_id}/tags',
        path: {
            artifact_id: data.artifactId
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * List Tags
 * @returns TagOut Successful Response
 * @throws ApiError
 */
export const listTagsApiV1TagsGet = (): CancelablePromise<ListTagsApiV1TagsGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/tags'
    });
};

/**
 * Get Me
 * @returns UserClaims Successful Response
 * @throws ApiError
 */
export const getMeApiV1UsersMeGet = (): CancelablePromise<GetMeApiV1UsersMeGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/users/me'
    });
};

/**
 * Get Profile
 * @returns UserProfileOut Successful Response
 * @throws ApiError
 */
export const getProfileApiV1UsersProfileGet = (): CancelablePromise<GetProfileApiV1UsersProfileGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/users/profile'
    });
};

/**
 * Create Profile
 * @param data The data for the request.
 * @param data.requestBody
 * @returns UserProfileOut Successful Response
 * @throws ApiError
 */
export const createProfileApiV1UsersProfilePost = (data: CreateProfileApiV1UsersProfilePostData): CancelablePromise<CreateProfileApiV1UsersProfilePostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/users/profile',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Get Queue
 * @param data The data for the request.
 * @param data.tags
 * @param data.mode
 * @returns QueueResponse Successful Response
 * @throws ApiError
 */
export const getQueueApiV1ReviewQueueGet = (data: GetQueueApiV1ReviewQueueGetData): CancelablePromise<GetQueueApiV1ReviewQueueGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/review/queue',
        query: {
            tags: data.tags,
            mode: data.mode
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Record Event
 * @param data The data for the request.
 * @param data.requestBody
 * @returns RecordEventResponse Successful Response
 * @throws ApiError
 */
export const recordEventApiV1ReviewEventsPost = (data: RecordEventApiV1ReviewEventsPostData): CancelablePromise<RecordEventApiV1ReviewEventsPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/review/events',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Get Mastery
 * @returns MasteryResponse Successful Response
 * @throws ApiError
 */
export const getMasteryApiV1ProfileMasteryGet = (): CancelablePromise<GetMasteryApiV1ProfileMasteryGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/profile/mastery'
    });
};

/**
 * Health
 * @returns string Successful Response
 * @throws ApiError
 */
export const healthHealthGet = (): CancelablePromise<HealthHealthGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/health'
    });
};