// This file is auto-generated by @hey-api/openapi-ts

export type ArtifactOut = {
    id: string;
    capture_id: string;
    artifact_type: string;
    content: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type CaptureCreate = {
    mode: string;
    raw_content?: (string | null);
    media_key?: (string | null);
};

export type CaptureOut = {
    id: string;
    user_id: string;
    mode: string;
    status: string;
    created_at: string;
};

export type FlashcardPair = {
    front: string;
    back: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type TagOut = {
    id: string;
    name: string;
    color: string;
    mastery_score: number;
};

export type TransformRequest = {
    text: string;
    tier?: 'free' | 'paid';
};

export type tier = 'free' | 'paid';

export type TransformResponse = {
    skill_name: string;
    cards: Array<FlashcardPair>;
    source_summary: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type TransformCaptureApiV1CapturesTransformPostData = {
    requestBody: TransformRequest;
};

export type TransformCaptureApiV1CapturesTransformPostResponse = (TransformResponse);

export type ListCapturesApiV1CapturesGetResponse = (Array<CaptureOut>);

export type CreateCaptureApiV1CapturesPostData = {
    requestBody: CaptureCreate;
};

export type CreateCaptureApiV1CapturesPostResponse = (CaptureOut);

export type GetCaptureApiV1CapturesCaptureIdGetData = {
    captureId: string;
};

export type GetCaptureApiV1CapturesCaptureIdGetResponse = (CaptureOut);

export type GetArtifactApiV1ArtifactsArtifactIdGetData = {
    artifactId: string;
};

export type GetArtifactApiV1ArtifactsArtifactIdGetResponse = (ArtifactOut);

export type ListArtifactsApiV1ArtifactsGetResponse = (Array<ArtifactOut>);

export type ListTagsApiV1TagsGetResponse = (Array<TagOut>);

export type GetTagApiV1TagsTagIdGetData = {
    tagId: string;
};

export type GetTagApiV1TagsTagIdGetResponse = (TagOut);

export type HealthHealthGetResponse = ({
    [key: string]: (string);
});